### ISSUE TITLE
[Enhancement] Search Bar

### ISSUE THREAD

**Issue by FolfyBlue** [VideoGameSmash12/HotbarsPlus#2]
I've already got something like 30 pages of saved hotbars, and searching for a specific item can be quite a hassle. Would a search bar be possible to implement? 
Kind of like the one in the "Search Items" tab.

**Comment by VideoGameSmash12** [comment]
I really like this idea. I'm not *entirely* sure if it would be possible to implement this in a practical sense (it would need to load every hotbar file individually and skim through its contents for that specific item) but this would be a very handy feature to have. I'll look into it.

**Comment by VideoGameSmash12** [comment]
> Having a look up table kinda like this: {"ItemName":HotBarIndex,"ItemName2":HotBarIndex}
Indexing them would be good for search-related functions, though I'll have to figure out how I'd implement this.

> Loading all of the NBT files into memory at game start, and using this. This would also solve the freeze upon load issues.
The only problem is that this could result in a serious memory problem if someone has a huge amount of hotbars with a bunch of NBT.

> Simply loading all the files one by one. This would be very laggy and ineficient, though.
The search function would most likely do this as it's the easiest to implement and would probably reduce the amount of RAM used overall (only speculating here) instead of having them all loaded into RAM. If I threw this operation onto a separate thread, I'm sure that would resolve the lag that would occur as a result.

**Comment by VideoGameSmash12** [comment]
Closing this. While I love the idea, it isn't something that would be practical to implement in my opinion.
